"""Small, auditable reference implementation for the VMCRG reproduction."""

from .artifacts import (
    atomic_write_json,
    atomic_write_npz,
    canonical_json_bytes,
    sha256_bytes,
    sha256_file,
    verified_promote_directory,
)
from .blockspin import block_majority, block_sums
from .baseline_certification import (
    certify_traditional_baseline,
    traditional_handoff_energy,
    traditional_handoff_from_values,
)
from .candidate_operators import (
    candidate_basis_metadata,
    candidate_even_shapes,
    published_survivor_indices,
)
from .exact import exact_nearest_neighbor_moments, nearest_neighbor_spectrum
from .fast import FastMultiOperatorBiasedMetropolis
from .formal_protocol import (
    freeze_formal_protocol,
    load_formal_execution_protocol,
)
from .formal import (
    build_formal_bundle_plan,
    classify_formal_root,
    run_formal_bundle,
)
from .exact_oracle import (
    compare_small_neural_gradients,
    ExactBlockingResult,
    enumerate_rectangular_blocking,
    exact_handoff_energy,
    exact_local_energy_delta,
    exact_objective,
    exact_objective_per_site,
    exact_parameter_gradient,
    flatten_mlp_gradient,
    jax_exact_neural_gradient,
    rectangular_ising_energy,
    target_distribution_distances,
)
from .hybrid_neural import (
    HybridNeuralVMCRGOptimizer,
    LinearNeuralBiasedMetropolis,
    ReferenceDistribution2D,
    UniformIsingReference2D,
)
from .five_round import five_round_pilot_bundle, run_five_round_chain
from .ising import IsingLattice, delta_nearest_neighbor_operator, nearest_neighbor_operator
from .issue28_protocol import (
    GaugeReferenceSpec,
    Issue28Protocol,
    NeuralSpec,
    PhysicalSetup,
    SeedBundle,
    SeedStream,
    TERMINAL_CLASSIFICATIONS,
    canonical_operator_basis_record,
    create_gauge_reference,
    load_issue28_protocol,
    operator_basis_sha256,
)
from .identity_certification import (
    classify_identity_results,
    identity_seed_records,
    run_identity_certification,
)
from .issue28_workflow import (
    BLOCKING_CLASSIFICATIONS,
    STAGE_ORDER,
    RunClassification,
    StageName,
    create_stage_manifest,
    current_code_sha256,
    gauge_spec_sha256,
    read_verified_stage_manifest,
    run_stage,
    verify_stage_dependencies,
)
from .mps_patch import MPSGradient, PatchMPS
from .mps_sampler import MPSBiasedMetropolis
from .mps_vmcrg import MPSOptimizationRecord, MPSVMCRGOptimizer
from .multi import MultiOperatorBiasedMetropolis
from .multi_optimizer import MultiOperatorOptimizer
from .neural_energy import D4EvenLocalMLP, LocalEnergyCache, MLPGradient
from .neural_checkpoint import (
    CheckpointExpectations,
    NeuralCheckpoint,
    load_neural_checkpoint,
    save_neural_checkpoint,
)
from .neural_hamiltonian import (
    NeuralHamiltonian,
    NeuralHamiltonianProposal,
    NeuralToNeuralBiasedMetropolis,
    NeuralToNeuralProposal,
)
from .optimizer import SingleOperatorOptimizer
from .objective import (
    BarIntervalResult,
    ChainSet,
    ObjectiveProtocol,
    ObjectiveResult,
    PairedObjectiveResult,
    bar_free_energy_difference,
    bar_from_exact_two_state_ensembles,
    bridge_objective,
    chain_jackknife,
    hierarchical_paired_bootstrap,
    objective_protocol_from_mapping,
    paired_objective_difference,
)
from .one_round import one_round_seed_bundle, run_one_round
from .operators import EVEN_SHAPES, ODD_SHAPES, OperatorBasis, OperatorShape, d4_orbit
from .paper_observables import (
    RGJacobianEstimate,
    covariance_matrices_from_sums,
    estimate_rg_jacobian,
    integrated_autocorrelation_time,
    leading_real_eigenvalue,
    normalized_connected_autocorrelation,
    scaling_dimensions,
)
from .sampler import BiasedMetropolis
from .training_protocol import (
    PolyakAverager,
    RobbinsMonroSchedule,
    TrainingProtocol,
    TrainingStopConfig,
    TrainingStopState,
    TrainingWindow,
    clip_mlp_gradient,
    load_training_protocol,
    model_parameters_finite,
)
from .patch_table import PatchEnergyCache, PatchLookupTable, decode_patch, encode_patch
from .power import estimate_five_seed_power
from .local_execution import (
    available_memory_bytes,
    local_host_provenance,
    resolve_worker_limit,
    run_bounded_process_schedule,
    run_local_formal,
)
from .rg import MajorityRGState

__all__ = [
    "atomic_write_json",
    "atomic_write_npz",
    "BiasedMetropolis",
    "BarIntervalResult",
    "ChainSet",
    "CheckpointExpectations",
    "FastMultiOperatorBiasedMetropolis",
    "freeze_formal_protocol",
    "build_formal_bundle_plan",
    "classify_formal_root",
    "five_round_pilot_bundle",
    "HybridNeuralVMCRGOptimizer",
    "IsingLattice",
    "MultiOperatorBiasedMetropolis",
    "MultiOperatorOptimizer",
    "MPSBiasedMetropolis",
    "MPSGradient",
    "MPSOptimizationRecord",
    "MPSVMCRGOptimizer",
    "MajorityRGState",
    "PatchEnergyCache",
    "PatchLookupTable",
    "PatchMPS",
    "D4EvenLocalMLP",
    "ExactBlockingResult",
    "compare_small_neural_gradients",
    "LinearNeuralBiasedMetropolis",
    "LocalEnergyCache",
    "MLPGradient",
    "ReferenceDistribution2D",
    "SingleOperatorOptimizer",
    "UniformIsingReference2D",
    "OperatorBasis",
    "OperatorShape",
    "ObjectiveProtocol",
    "ObjectiveResult",
    "one_round_seed_bundle",
    "run_one_round",
    "run_five_round_chain",
    "run_formal_bundle",
    "PairedObjectiveResult",
    "RGJacobianEstimate",
    "EVEN_SHAPES",
    "ODD_SHAPES",
    "block_majority",
    "block_sums",
    "bar_free_energy_difference",
    "bar_from_exact_two_state_ensembles",
    "bridge_objective",
    "certify_traditional_baseline",
    "canonical_json_bytes",
    "candidate_basis_metadata",
    "candidate_even_shapes",
    "chain_jackknife",
    "covariance_matrices_from_sums",
    "exact_nearest_neighbor_moments",
    "enumerate_rectangular_blocking",
    "exact_handoff_energy",
    "exact_local_energy_delta",
    "exact_objective",
    "exact_objective_per_site",
    "exact_parameter_gradient",
    "flatten_mlp_gradient",
    "jax_exact_neural_gradient",
    "delta_nearest_neighbor_operator",
    "d4_orbit",
    "estimate_rg_jacobian",
    "estimate_five_seed_power",
    "available_memory_bytes",
    "local_host_provenance",
    "resolve_worker_limit",
    "run_bounded_process_schedule",
    "run_local_formal",
    "decode_patch",
    "encode_patch",
    "integrated_autocorrelation_time",
    "hierarchical_paired_bootstrap",
    "leading_real_eigenvalue",
    "nearest_neighbor_spectrum",
    "nearest_neighbor_operator",
    "normalized_connected_autocorrelation",
    "published_survivor_indices",
    "rectangular_ising_energy",
    "scaling_dimensions",
    "target_distribution_distances",
    "sha256_bytes",
    "sha256_file",
    "traditional_handoff_energy",
    "traditional_handoff_from_values",
    "verified_promote_directory",
    "GaugeReferenceSpec",
    "Issue28Protocol",
    "classify_identity_results",
    "identity_seed_records",
    "run_identity_certification",
    "StageName",
    "RunClassification",
    "STAGE_ORDER",
    "BLOCKING_CLASSIFICATIONS",
    "NeuralSpec",
    "NeuralCheckpoint",
    "NeuralHamiltonian",
    "NeuralHamiltonianProposal",
    "NeuralToNeuralBiasedMetropolis",
    "NeuralToNeuralProposal",
    "PhysicalSetup",
    "SeedBundle",
    "SeedStream",
    "TERMINAL_CLASSIFICATIONS",
    "canonical_operator_basis_record",
    "create_gauge_reference",
    "load_issue28_protocol",
    "load_formal_execution_protocol",
    "create_stage_manifest",
    "current_code_sha256",
    "gauge_spec_sha256",
    "read_verified_stage_manifest",
    "run_stage",
    "verify_stage_dependencies",
    "load_neural_checkpoint",
    "operator_basis_sha256",
    "objective_protocol_from_mapping",
    "paired_objective_difference",
    "save_neural_checkpoint",
    "PolyakAverager",
    "RobbinsMonroSchedule",
    "TrainingProtocol",
    "TrainingStopConfig",
    "TrainingStopState",
    "TrainingWindow",
    "clip_mlp_gradient",
    "load_training_protocol",
    "model_parameters_finite",
]
