function result = run_cpmc_bridge(config_input)
%RUN_CPMC_BRIDGE Load frozen ALF orbitals and invoke audited CPMC-Lab.

if ischar(config_input) || isstring(config_input)
    config = jsondecode(fileread(config_input));
else
    config = config_input;
end
required = {'package_dir','trial_dir','output_dir','run_id','mode', ...
    'seed','ltrot','N_wlk','N_blksteps','N_eqblk','N_blk', ...
    'itv_modsvd','itv_pc','itv_Em','contract_hashes'};
for index = 1:numel(required)
    assert(isfield(config,required{index}), ...
        'bridge:config:missing','Missing config field %s',required{index});
end
addpath(config.package_dir);
addpath(fileparts(mfilename('fullpath')));

N_sites=16;
N_up=8;
N_dn=8;
I_up_alf=read_orbitals(fullfile(config.trial_dir,'trial_I_up.dat'), ...
    N_sites,N_up);
I_dn_alf=read_orbitals(fullfile(config.trial_dir,'trial_I_down.dat'), ...
    N_sites,N_dn);
T_up_alf=read_orbitals(fullfile(config.trial_dir,'trial_T_up.dat'), ...
    N_sites,N_up);
T_dn_alf=read_orbitals(fullfile(config.trial_dir,'trial_T_down.dat'), ...
    N_sites,N_dn);
site_map=readmatrix(fullfile(config.trial_dir,'site_map.dat'), ...
    'FileType','text');
assert(isequal(size(site_map),[N_sites,4]), ...
    'bridge:siteMap:shape','site_map.dat has wrong shape');
assert(isequal(sort(site_map(:,1)),(1:N_sites)') && ...
    isequal(sort(site_map(:,2)),(0:N_sites-1)'), ...
    'bridge:siteMap:permutation','site map is not a permutation');
I_up=zeros(size(I_up_alf)); I_dn=zeros(size(I_dn_alf));
T_up=zeros(size(T_up_alf)); T_dn=zeros(size(T_dn_alf));
for alf=1:N_sites
    cpp=site_map(alf,2)+1;
    I_up(cpp,:)=I_up_alf(alf,:);
    I_dn(cpp,:)=I_dn_alf(alf,:);
    T_up(cpp,:)=T_up_alf(alf,:);
    T_dn(cpp,:)=T_dn_alf(alf,:);
end

params=struct( ...
    'Lx',4,'Ly',4,'Lz',1,'N_up',N_up,'N_dn',N_dn, ...
    'kx',0,'ky',0,'kz',0,'U',4,'tx',1,'ty',1,'tz',0, ...
    'deltau',0.05,'N_wlk',config.N_wlk, ...
    'N_blksteps',config.N_blksteps,'N_eqblk',config.N_eqblk, ...
    'N_blk',config.N_blk,'itv_modsvd',config.itv_modsvd, ...
    'itv_pc',config.itv_pc,'itv_Em',config.itv_Em);
opts=struct( ...
    'Phi_init',[I_up,I_dn],'Phi_trial',[T_up,T_dn], ...
    'rng_seed',config.seed,'mode',config.mode, ...
    'total_steps',config.ltrot,'diagnostics',true, ...
    'output_dir',config.output_dir,'run_id',config.run_id, ...
    'contract_hashes',config.contract_hashes,'ltrot',config.ltrot);
if isfield(config,'diagnostics')
    opts.diagnostics=logical(config.diagnostics);
end
if isfield(config,'prefix_logq_floor')
    opts.prefix_logq_floor=config.prefix_logq_floor;
end
[E_ave,E_err,savedFileName,diag]=CPMC_Bridge(params,opts);
result=struct('E_ave',E_ave,'E_err',E_err, ...
    'savedFileName',savedFileName,'diag',diag);
end
