function opts = validate_bridge_opts(opts, N_sites, N_up, N_dn)
%VALIDATE_BRIDGE_OPTS Validate mixed-boundary and diagnostic run options.

arguments
    opts (1,1) struct
    N_sites (1,1) double {mustBeInteger,mustBePositive}
    N_up (1,1) double {mustBeInteger,mustBePositive}
    N_dn (1,1) double {mustBeInteger,mustBePositive}
end

required = {'Phi_init','Phi_trial','rng_seed','mode','total_steps', ...
    'diagnostics','output_dir','run_id','contract_hashes','ltrot'};
for index = 1:numel(required)
    assert(isfield(opts, required{index}), 'bridge:opts:missing', ...
        'Missing bridge option: %s', required{index});
end
N_par = N_up + N_dn;
assert(isequal(size(opts.Phi_init), [N_sites, N_par]), ...
    'bridge:opts:initShape', 'Phi_init has the wrong shape');
assert(isequal(size(opts.Phi_trial), [N_sites, N_par]), ...
    'bridge:opts:trialShape', 'Phi_trial has the wrong shape');
assert(isreal(opts.Phi_init) && all(isfinite(opts.Phi_init), 'all'), ...
    'bridge:opts:initFinite', 'Phi_init must be finite and real');
assert(isreal(opts.Phi_trial) && all(isfinite(opts.Phi_trial), 'all'), ...
    'bridge:opts:trialFinite', 'Phi_trial must be finite and real');

blocks = {
    opts.Phi_init(:,1:N_up), ...
    opts.Phi_init(:,N_up+1:N_par), ...
    opts.Phi_trial(:,1:N_up), ...
    opts.Phi_trial(:,N_up+1:N_par)
};
for index = 1:numel(blocks)
    residual = norm(blocks{index}' * blocks{index} - ...
        eye(size(blocks{index},2)), inf);
    assert(residual < 1e-10, 'bridge:opts:orthonormal', ...
        'Orbital block %d is not orthonormal (%.3e)', index, residual);
end
overlap_up = det(opts.Phi_trial(:,1:N_up)' * ...
    opts.Phi_init(:,1:N_up));
overlap_dn = det(opts.Phi_trial(:,N_up+1:N_par)' * ...
    opts.Phi_init(:,N_up+1:N_par));
assert(isreal(overlap_up) && isreal(overlap_dn) && ...
    overlap_up > 1e-10 && overlap_dn > 1e-10, ...
    'bridge:opts:overlap', ...
    'Each spin trial/initial overlap must be real, positive, and >1e-10');

valid_modes = {'production','fixed_horizon','proposal_only'};
assert(any(strcmp(opts.mode, valid_modes)), 'bridge:opts:mode', ...
    'Unknown bridge mode: %s', opts.mode);
positive_integers = {'rng_seed','total_steps','ltrot'};
for index = 1:numel(positive_integers)
    value = opts.(positive_integers{index});
    assert(isscalar(value) && isfinite(value) && value > 0 && ...
        value == floor(value), 'bridge:opts:integer', ...
        '%s must be a positive integer', positive_integers{index});
end
assert(islogical(opts.diagnostics) && isscalar(opts.diagnostics), ...
    'bridge:opts:diagnostics','diagnostics must be scalar logical');
assert(ischar(opts.output_dir) || isstring(opts.output_dir), ...
    'bridge:opts:output','output_dir must be text');
assert(ischar(opts.run_id) || isstring(opts.run_id), ...
    'bridge:opts:runid','run_id must be text');
assert(isfield(opts.contract_hashes,'selected_projection'), ...
    'bridge:opts:hash','Missing selected_projection contract hash');
end
