#!/usr/bin/env julia
# dump_legacy_inventory.jl
#
# Solver-free snapshot of the legacy SpectralGap basis + Hamiltonian inventories
# for the two validated small cases:
#   - 1D transverse-field Ising, N=9, g=0.5, d=2   (the example.jl TFIM benchmark)
#   - Kagome Heisenberg, N=5,                d=2   (the smallest example.jl cluster)
#
# Purpose: reference data for spectralgap-refactor-plan.md acceptance test 6
# ("Legacy Ising/Kagome wrappers reproduce old basis/block inventories") and for
# coefficient-by-coefficient comparison against the generic adapter
# (GenericGapModel.legacy_ncpoly_data).
#
# It calls ONLY ncpoly construction + get_basis/get_kagome_basis/get_bulkbasis/
# get_kagome_bulkbasis. It does NOT call certify_*_gap, so it does not hit the
# Mosek-11 zero-dim-PSD bug. No solver is loaded.
#
# Run on SCNet:
#   julia --project=julia-env dump_legacy_inventory.jl > legacy_inventory.txt
#
# Status: written from reading src/basicfunction.jl + example/example.jl; NOT yet
# executed (no local solver environment). Validate the first run's output against
# the closed-form sizes noted in legacy-inventory-spec.md.

using SpectralGap

const OUT = stdout

function println_kv(k, v)
    println(OUT, k, " = ", v)
end

# Dump a basis block: a Vector of (word::Vector{Int}, aux::Vector{Vector{Int}}).
function dump_basis_block(name, block)
    println_kv(name * ".length", length(block))
    for (i, entry) in enumerate(block)
        word, aux = entry
        println(OUT, "    ", name, "[", i, "].word = ", word)
        if !isempty(aux)
            println(OUT, "    ", name, "[", i, "].aux  = ", aux)
        end
    end
end

function dump_ising(N, g, d)
    println(OUT, "=========================================================")
    println(OUT, "[model] 1D-transverse-field-Ising   N=$N  g=$g  d=$d")
    println(OUT, "=========================================================")
    # H construction copied verbatim from example/example.jl
    H = ncpoly([[3*[i; i+1] for i in 1:N-1]; [[3i - 2] for i in 1:N]],
               [-ones(N - 1); g * ones(N)])
    println_kv("H.supp_count", length(H.supp))
    for (i, (s, c)) in enumerate(zip(H.supp, H.coe))
        println(OUT, "    H[", i, "] = ", c, " * ", s)
    end
    # Basis blocks (two sign-symmetry sectors, label 1 and 2)
    basis1 = SpectralGap.get_basis(N, d; label = 1)
    basis2 = SpectralGap.get_basis(N, d; label = 2)
    gbasis1 = SpectralGap.get_bulkbasis(N, d - 1; label = 1)
    gbasis2 = SpectralGap.get_bulkbasis(N, d - 1; label = 2)
    dump_basis_block("basis.label1", basis1)
    dump_basis_block("basis.label2", basis2)
    dump_basis_block("gbasis.label1", gbasis1)
    dump_basis_block("gbasis.label2", gbasis2)
    println(OUT)
end

function dump_kagome(N, d)
    println(OUT, "=========================================================")
    println(OUT, "[model] kagome-Heisenberg   N=$N  d=$d")
    println(OUT, "=========================================================")
    # N=5 geometry from example/example.jl
    triples = [[1, 2, 3], [1, 4, 5]]
    edges = Vector{Int}[]
    inner_triples = triples          # N=5: inner == outer (smallest patch)
    inner_edges = edges
    println_kv("triples", triples)
    # H construction copied verbatim from example/example.jl (0.25 coeff = spin-1/2 factor)
    H = ncpoly(
        vcat([
            [[3*a[1]-2; 3*a[2]-2], [3*a[1]-1; 3*a[2]-1], [3*a[1]; 3*a[2]],
             [3*a[1]-2; 3*a[3]-2], [3*a[1]-1; 3*a[3]-1], [3*a[1]; 3*a[3]],
             [3*a[2]-2; 3*a[3]-2], [3*a[2]-1; 3*a[3]-1], [3*a[2]; 3*a[3]]] for a in triples]...),
        0.25 * ones(9 * length(triples)))
    println_kv("H.supp_count", length(H.supp))
    for (i, (s, c)) in enumerate(zip(H.supp, H.coe))
        println(OUT, "    H[", i, "] = ", c, " * ", s)
    end
    basis1 = SpectralGap.get_kagome_basis(N, triples, edges, d; label = 1)
    basis2 = SpectralGap.get_kagome_basis(N, triples, edges, d; label = 2)
    gbasis1 = SpectralGap.get_kagome_bulkbasis(N, inner_triples, inner_edges, d - 1; label = 1)
    gbasis2 = SpectralGap.get_kagome_bulkbasis(N, inner_triples, inner_edges, d - 1; label = 2)
    dump_basis_block("basis.label1", basis1)
    dump_basis_block("basis.label2", basis2)
    dump_basis_block("gbasis.label1", gbasis1)
    dump_basis_block("gbasis.label2", gbasis2)
    println(OUT)
end

println(OUT, "# Legacy SpectralGap inventory dump")
println(OUT, "# Generated by dump_legacy_inventory.jl")
println(OUT, "# Format: deterministic plain text; each basis entry is (word, aux).")
println(OUT)

dump_ising(9, 0.5, 2)
dump_kagome(5, 2)

println(OUT, "# end of dump")
