#!/usr/bin/env python3
"""Generate a synthetic Liu-2026 ``input.in`` from the neutral-atom simulator.

The bridge deliberately keeps three evidence classes separate:

1. the independently reoptimized ten-state waveform and Hessian;
2. finite-shot public observations generated by ``cs_tweezer_sim``;
3. literal paper anchors used only where unpublished experimental inputs
   prevent an independent prediction.

It does not claim to recover the authors' pulse array, MQDT table, or raw
experimental shots.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
from dataclasses import asdict, replace
from pathlib import Path
from typing import Any, Iterable

import numpy as np
from scipy import optimize

from cs_tweezer_sim import (
    ExperimentProgram,
    ExperimentRuntime,
    Measure,
    Prepare,
    SampledWaveform,
    SequentialNdssrObservationModel,
    liu_2026_yb171_four_level_profile,
    load_published_fluorescence_calibration,
)
from cs_tweezer_sim.gate_metrics import (
    evaluate_coherent_gate,
    evaluate_open_system_gate,
)
from cs_tweezer_sim.config import TransitionCouplingSpec
from cs_tweezer_sim.multilevel_config import PairInteractionSpec
from cs_tweezer_sim.qutip_multilevel_backend import QutipMultilevelBackend
from cs_tweezer_sim.waveform_compiler import compile_sampled_fields


SEED = 260605060
SHOTS = 50_000
TWOPI = 2.0 * math.pi
FINITE_BLOCKADE_ANCHOR = 1.6e-4


def progress(message: str) -> None:
    print(message, flush=True)


def read_json(path: Path) -> Any:
    with path.open(encoding="utf-8") as handle:
        return json.load(handle)


def json_safe(value: Any) -> Any:
    """Return a strict-JSON representation, mapping undefined floats to null."""

    if isinstance(value, dict):
        return {key: json_safe(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [json_safe(item) for item in value]
    if isinstance(value, float) and not math.isfinite(value):
        return None
    return value


def write_json(path: Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    with temporary.open("w", encoding="utf-8") as handle:
        json.dump(
            json_safe(value),
            handle,
            indent=2,
            ensure_ascii=False,
            allow_nan=False,
        )
        handle.write("\n")
    temporary.replace(path)


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def write_csv(path: Path, rows: Iterable[dict[str, Any]]) -> None:
    materialized = list(rows)
    if not materialized:
        raise ValueError(f"refusing to write an empty table: {path}")
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    with temporary.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(materialized[0]))
        writer.writeheader()
        writer.writerows(materialized)
    temporary.replace(path)


def bool_text(value: bool) -> str:
    return "true" if value else "false"


def sampled_gate_waveform(
    archive_path: Path, *, intervals: int | None = None, scale: float = 1.0
) -> SampledWaveform:
    with np.load(archive_path) as archive:
        times = np.asarray(archive["times_us"], dtype=float)
        amplitude = np.asarray(archive["amplitude"], dtype=float)
        phase = np.asarray(archive["phase_unwrapped"], dtype=float)
        backend = str(archive["backend"].item())
        phase_coefficients = np.asarray(
            archive["phase_coefficients"], dtype=float
        )
        amplitude_coefficients = np.asarray(
            archive["amplitude_coefficients"], dtype=float
        )
    duration = float(times[-1] - times[0])
    if backend == "source_phase" and intervals is None:
        intervals = len(phase_coefficients)
        return SampledWaveform(
            dt_us=duration / intervals,
            amplitude_rad_per_us=tuple(
                float(scale * TWOPI * 6.0 * x)
                for x in amplitude_coefficients
            ),
            phase_rad=tuple(float(x) for x in phase_coefficients),
            detuning_rad_per_us=(0.0,) * intervals,
        )
    intervals = intervals or 800
    dt = duration / intervals
    centers = times[0] + (np.arange(intervals) + 0.5) * dt
    amplitude_rad_per_us = (
        scale * TWOPI * 6.0 * np.interp(centers, times, amplitude)
    )
    phase_rad = np.interp(centers, times, phase)
    return SampledWaveform(
        dt_us=dt,
        amplitude_rad_per_us=tuple(float(x) for x in amplitude_rad_per_us),
        phase_rad=tuple(float(x) for x in phase_rad),
        detuning_rad_per_us=(0.0,) * intervals,
    )


def gate_program(waveform: SampledWaveform, name: str) -> ExperimentProgram:
    return compile_sampled_fields(
        n_atoms=2,
        fields={"rydberg_302": waveform},
        targets={"rydberg_302": (0, 1)},
        measure=False,
        name=name,
    )


def effective_double_rydberg_config(
    blockade_rad_per_us: float, *, include_decay: bool
) -> Any:
    """Apply B_eff to every double-Rydberg product in the four-level model."""

    config = liu_2026_yb171_four_level_profile(
        n_atoms=2,
        include_effective_rydberg_decay=include_decay,
        nominal_rr_interaction_rad_per_us=None,
    )
    interactions = (
        PairInteractionSpec(
            "r", "r", blockade_rad_per_us, label="effective-double-r"
        ),
        PairInteractionSpec(
            "r",
            "r_prime",
            blockade_rad_per_us,
            symmetric=True,
            label="effective-mixed-r",
        ),
        PairInteractionSpec(
            "r_prime",
            "r_prime",
            blockade_rad_per_us,
            label="effective-double-r-prime",
        ),
    )
    energies = dict(config.model.static_level_energies_rad_per_us)
    energies["r_prime"] = TWOPI * 16.1
    channels = dict(config.channels)
    channels["rydberg_302"] = replace(
        channels["rydberg_302"],
        additional_transition_couplings=(
            TransitionCouplingSpec("0_r_prime", -1.0),
        ),
    )
    return replace(
        config,
        channels=channels,
        model=replace(
            config.model,
            static_level_energies_rad_per_us=energies,
            pair_interactions=interactions,
        ),
    )


def coherent_metrics(
    waveform: SampledWaveform,
    blockade_rad_per_us: float,
    *,
    target: np.ndarray | None = None,
) -> Any:
    backend = QutipMultilevelBackend(
        effective_double_rydberg_config(
            blockade_rad_per_us, include_decay=False
        )
    )
    return evaluate_coherent_gate(
        backend, gate_program(waveform, "liu-2026-coherent-validator"), target=target
    )


def calibrate_blockade(
    waveform: SampledWaveform,
) -> tuple[float, Any, list[dict[str, float]]]:
    """Fit one effective R^-6 coefficient to the paper's 1.6e-4 anchor."""

    reference_blockade = TWOPI * 10_000.0
    reference = coherent_metrics(waveform, reference_blockade)
    target = reference.target
    reference_error = 1.0 - reference.average_fidelity
    evaluations: list[dict[str, float]] = []

    def objective(log_b_mhz: float) -> float:
        b_mhz = math.exp(log_b_mhz)
        metric = coherent_metrics(waveform, TWOPI * b_mhz, target=target)
        excess = max(
            0.0, (1.0 - metric.average_fidelity) - reference_error
        )
        evaluations.append(
            {
                "blockade_mhz": b_mhz,
                "coherent_infidelity": 1.0 - metric.average_fidelity,
                "excess_over_reference": excess,
            }
        )
        return (math.log10(max(excess, 1e-15))
                - math.log10(FINITE_BLOCKADE_ANCHOR)) ** 2

    result = optimize.minimize_scalar(
        objective,
        bounds=(math.log(5.0), math.log(10_000.0)),
        method="bounded",
        options={"xatol": 2e-3, "maxiter": 32},
    )
    blockade_mhz = math.exp(float(result.x))
    calibrated = coherent_metrics(waveform, TWOPI * blockade_mhz, target=target)
    return blockade_mhz, calibrated, evaluations


def open_system_metrics(
    waveform: SampledWaveform,
    blockade_mhz: float,
    target: np.ndarray,
) -> Any:
    backend = QutipMultilevelBackend(
        effective_double_rydberg_config(
            TWOPI * blockade_mhz, include_decay=True
        )
    )
    return evaluate_open_system_gate(
        backend,
        gate_program(waveform, "liu-2026-open-system-validator"),
        target=target,
    )


def fluorescence_model(sim_repo: Path) -> SequentialNdssrObservationModel:
    path = (
        sim_repo
        / "Cold_Atom Gate Simu_Platform"
        / "data"
        / "published"
        / "radnaev_2025_ndssr_fit.json"
    )
    expected = path.with_suffix(path.suffix + ".sha256").read_text().strip()
    calibration, _, _ = load_published_fluorescence_calibration(
        path, expected_sha256=expected
    )
    return SequentialNdssrObservationModel(
        calibration,
        bright_labels=frozenset({"1"}),
        lost_labels=frozenset({"R", "L"}),
    )


def generate_imaging_rows(sim_repo: Path) -> list[dict[str, Any]]:
    backend = QutipMultilevelBackend(
        liu_2026_yb171_four_level_profile(
            n_atoms=1, include_effective_rydberg_decay=False
        )
    )
    runtime = ExperimentRuntime(
        backend, seed=SEED, observation_model=fluorescence_model(sim_repo)
    )
    rows: list[dict[str, Any]] = []
    shots_per_state = SHOTS // 2
    shot_id = 0
    for state in ("0", "1"):
        result = runtime.execute(
            ExperimentProgram((Prepare(state), Measure()), f"prepare-{state}"),
            shots=shots_per_state,
        )
        for record in result.shot_readouts:
            shot_id += 1
            atom = record.atoms[0]
            rows.append(
                {
                    "shot_id": shot_id,
                    "prepared_state": state,
                    "first_image_photon_count": atom.state_signal_photoelectrons,
                    "second_image_photon_count": atom.occupancy_signal_photoelectrons,
                    "state_assignment": atom.classified_state,
                    "loss_assignment": bool_text(not atom.retained),
                }
            )
    return rows


def rb_rows(
    *,
    depths: tuple[int, ...],
    fidelity: float,
    loss_per_gate: float,
    shots: int,
    rng: np.random.Generator,
    two_qubit: bool,
) -> list[dict[str, Any]]:
    dimension = 4 if two_qubit else 2
    decay = float(np.clip((dimension * fidelity - 1.0) / (dimension - 1.0), 0, 1))
    per_depth = shots // len(depths)
    rows: list[dict[str, Any]] = []
    shot_id = 0
    for depth in depths:
        postselected_success = 1.0 / dimension + (
            1.0 - 1.0 / dimension
        ) * decay**depth
        loss_probability = 1.0 - (1.0 - loss_per_gate) ** depth
        for local_id in range(per_depth):
            shot_id += 1
            loss = bool(rng.random() < loss_probability)
            success = bool((not loss) and rng.random() < postselected_success)
            common = {
                "sequence_id": local_id + 1,
                "shot_id": shot_id,
                "success": bool_text(success),
                "postselection_flag": bool_text(not loss),
            }
            if two_qubit:
                rows.append(
                    {
                        "rb_circuit_depth": depth,
                        **common,
                        "loss": bool_text(loss),
                    }
                )
            else:
                rows.append(
                    {
                        "rb_depth": depth,
                        **common,
                        "survival": int(not loss),
                    }
                )
    return rows


def waveform_rows(theory_dir: Path) -> list[dict[str, Any]]:
    path = theory_dir / "data" / "fig4_synthetic_aom.npz"
    with np.load(path) as archive:
        t = np.asarray(archive["bin_centers_us"], dtype=float)
        ideal = np.asarray(archive["ideal"], dtype=complex)
        before = np.asarray(archive["before_output"], dtype=complex)
        after = np.asarray(archive["after_output"], dtype=complex)
    omega0 = TWOPI * 6.0
    rows = []
    for index, time_us in enumerate(t):
        wrapped = float(np.angle(after[index]))
        unwrapped = float(np.unwrap(np.angle(after))[index])
        rows.append(
            {
                "time_us": time_us,
                "ideal_amplitude": abs(ideal[index]) / omega0,
                "before_amplitude": abs(before[index]) / omega0,
                "after_amplitude": abs(after[index]) / omega0,
                "ideal_intensity": (abs(ideal[index]) / omega0) ** 2,
                "before_intensity": (abs(before[index]) / omega0) ** 2,
                "after_intensity": (abs(after[index]) / omega0) ** 2,
                "wrapped_phase": wrapped,
                "unwrapped_phase": unwrapped,
                "measurement_uncertainty": 1.0 / math.sqrt(SHOTS),
            }
        )
    return rows


def hessian_panel_rows(theory_dir: Path) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    spectrum = read_csv(theory_dir / "data" / "fig3_hessian_spectrum.csv")
    eigenvalue = {int(float(row["mode"])): float(row["eigenvalue"]) for row in spectrum}
    scans = read_csv(theory_dir / "data" / "fig4_synthetic_scans.csv")
    sensitivity_rows = []
    for row in scans:
        mode = int(float(row["mode"]))
        if (
            int(float(row["cycle"])) == 1
            and int(float(row["expansion"])) == 0
            and mode <= 10
        ):
            sensitivity_rows.append(
                {
                    "mode": mode,
                    "coefficient": float(row["scan_coefficient"]),
                    "rb_fidelity_or_error": float(
                        row["synthetic_observed_total_error"]
                    ),
                    "uncertainty": float(row["synthetic_uncertainty"]),
                    "theory_sensitivity": eigenvalue[mode],
                }
            )

    rng = np.random.default_rng(SEED + 3)
    decomposition_rows = []
    coefficient = 0.02
    channels = ("alpha00", "alpha01", "alpha11")
    states = ("00", "01", "11")
    labels = ("00_to_Wprime", "01_to_0r", "11_to_W")
    for row in spectrum:
        mode = int(float(row["mode"]))
        if mode > 10:
            continue
        channel_values = np.asarray(
            [max(float(row[name]), 0.0) for name in channels]
        )
        channel_index = int(np.argmax(channel_values))
        leakage_probability = float(
            np.clip(0.5 * coefficient**2 * np.sum(channel_values), 1e-7, 0.2)
        )
        leakage_count = int(rng.binomial(SHOTS, leakage_probability))
        leakage = (leakage_count + 0.5) / (SHOTS + 1.0)
        leakage_sigma = math.sqrt(leakage * (1.0 - leakage) / (SHOTS + 2.0))
        theta = float(row["theta"])
        phase = coefficient * math.copysign(math.sqrt(abs(theta)), theta)
        phase_sigma = 1.0 / math.sqrt(SHOTS)
        decomposition_rows.append(
            {
                "mode": mode,
                "coefficient": coefficient,
                "initial_computational_state": states[channel_index],
                "leakage_channel": labels[channel_index],
                "measured_leakage": leakage,
                "leakage_uncertainty": leakage_sigma,
                "ramsey_phase": phase,
                "ramsey_phase_uncertainty": phase_sigma,
            }
        )
    return sensitivity_rows, decomposition_rows


def closed_loop_rows(theory_dir: Path) -> list[dict[str, Any]]:
    rows = []
    for row in read_csv(theory_dir / "data" / "fig4_synthetic_scans.csv"):
        if (
            int(float(row["cycle"])) <= 4
            and int(float(row["mode"])) in (1, 5, 10)
            and int(float(row["expansion"])) == 0
        ):
            rows.append(
                {
                    "cycle": int(float(row["cycle"])),
                    "mode": int(float(row["mode"])),
                    "scan_coefficient": float(row["scan_coefficient"]),
                    "gate_error": float(row["synthetic_observed_total_error"]),
                    "uncertainty": float(row["synthetic_uncertainty"]),
                    "selected_optimum": bool_text(
                        row["selected_optimum"].lower() == "true"
                    ),
                }
            )
    return rows


def intensity_rows(theory_dir: Path) -> list[dict[str, Any]]:
    rows = []
    for row in read_csv(theory_dir / "data" / "fig4_intensity_scaling.csv"):
        if (
            row["fidelity_convention"] == "pointwise_cz_equivalent"
            and row["range"] == "paper_range"
        ):
            error = max(float(row["infidelity_raw"]), 0.5 / SHOTS)
            rows.append(
                {
                    "gate_type": (
                        "AR"
                        if row["gate"].startswith("AR ")
                        else "same_duration_nonrobust_surrogate"
                    ),
                    "intensity_ratio": float(row["intensity_ratio"]),
                    "gate_error": error,
                    "uncertainty": math.sqrt(error * (1.0 - error) / SHOTS),
                    "fidelity_convention": "pointwise_cz_equivalent",
                }
            )
    return rows


def stability_rows(
    theory_dir: Path, baseline_error: float, rng: np.random.Generator
) -> list[dict[str, Any]]:
    intensity = [
        row
        for row in intensity_rows(theory_dir)
        if row["gate_type"] == "AR"
    ]
    x = np.asarray([row["intensity_ratio"] for row in intensity])
    y = np.asarray([row["gate_error"] for row in intensity])
    order = np.argsort(x)
    x, y = x[order], y[order]
    floor = float(np.min(y))
    rows = []
    for index, elapsed in enumerate(np.linspace(0.0, 10.0, 21)):
        ratio = 1.0 + 0.015 * math.sin(0.9 * elapsed) + rng.normal(0.0, 0.003)
        coherent_excess = max(float(np.interp(ratio, x, y)) - floor, 0.0)
        probability = float(np.clip(baseline_error + coherent_excess, 0, 1))
        failures = int(rng.binomial(SHOTS, probability))
        estimate = (failures + 0.5) / (SHOTS + 1.0)
        rows.append(
            {
                "elapsed_time": elapsed,
                "gate_error": estimate,
                "uncertainty": math.sqrt(
                    estimate * (1.0 - estimate) / (SHOTS + 2.0)
                ),
                "calibration_or_reoptimization_event": (
                    "initial" if index == 0 else "none"
                ),
            }
        )
    return rows


def error_budget_rows(
    coherent_infidelity: float, open_metrics: Any
) -> list[dict[str, Any]]:
    lifetime_raw = max(
        0.0, (1.0 - open_metrics.raw_average_fidelity) - coherent_infidelity
    )
    lifetime_post = max(
        0.0,
        (1.0 - open_metrics.weighted_conditional_fidelity)
        - coherent_infidelity,
    )
    return [
        {
            "noise_source": "effective_lifetime",
            "raw_contribution": lifetime_raw,
            "postselected_contribution": lifetime_post,
            "uncertainty": 2e-5,
            "parameter_source": "simulator: 42 us lifetime, 90% erasure",
        },
        {
            "noise_source": "effective_finite_blockade",
            "raw_contribution": FINITE_BLOCKADE_ANCHOR,
            "postselected_contribution": 3e-5,
            "uncertainty": 2e-5,
            "parameter_source": "B0 calibrated to paper raw 1.6e-4 anchor",
        },
        {
            "noise_source": "Doppler",
            "raw_contribution": 3.7e-4,
            "postselected_contribution": 2.8e-4,
            "uncertainty": 2e-5,
            "parameter_source": "paper-reported; no trap position samples",
        },
        {
            "noise_source": "laser_phase_noise",
            "raw_contribution": 1.4e-4,
            "postselected_contribution": 1.0e-4,
            "uncertainty": 2e-5,
            "parameter_source": "paper-reported; PSD unavailable",
        },
        {
            "noise_source": "laser_amplitude_noise",
            "raw_contribution": 1.0e-5,
            "postselected_contribution": float("nan"),
            "uncertainty": 2e-5,
            "parameter_source": "paper-reported; PSD unavailable",
        },
    ]


def pulse_waveform_rows(archive_path: Path) -> list[dict[str, Any]]:
    with np.load(archive_path) as archive:
        times = np.asarray(archive["times_us"], dtype=float)
        amplitude = TWOPI * 6.0 * np.asarray(archive["amplitude"], dtype=float)
        phase = np.asarray(archive["phase_unwrapped"], dtype=float)
    return [
        {
            "time_us": time,
            "amplitude_rad_per_us": amp,
            "phase_rad": phi,
        }
        for time, amp, phi in zip(times, amplitude, phase)
    ]


def manifest(
    sim_repo: Path, generated: Path, panel_paths: dict[str, Path]
) -> dict[str, Any]:
    template = read_json(sim_repo / "reproduce" / "input.in")
    physical = template["physical_model"]
    physical["provenance"] = (
        "paper-stated values plus independently reoptimized pulse and explicit "
        "effective-model placeholders"
    )
    physical["microscopic_inputs"]["pulse_waveform"] = {
        "source": "csv",
        "path": str(
            panel_paths["pulse_waveform"].relative_to(generated.parent)
        ),
        "provenance": (
            "independent source-constrained 400-bin reoptimization; not the "
            "authors' unpublished waveform"
        ),
    }
    panels = {
        name: {
            "source": "csv",
            "path": str(path.relative_to(generated.parent)),
            "provenance": "simulator/theory synthetic data; not experimental",
        }
        for name, path in panel_paths.items()
        if name != "pulse_waveform"
    }
    return {
        "schema_version": 2,
        "provenance": "synthetic demonstration",
        "description": (
            "Finite-shot digital-twin data generated locally from "
            "cs_tweezer_sim plus an equivalent Figure-3 reoptimization. "
            "No author raw shots, AR array, or MQDT table are claimed."
        ),
        "physical_model": physical,
        "panels": panels,
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--sim-repo", type=Path, required=True)
    parser.add_argument("--theory-run-dir", type=Path, required=True)
    parser.add_argument("--figure2-run-dir", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    sim_repo = args.sim_repo.resolve()
    theory_dir = args.theory_run_dir.resolve()
    figure2_dir = args.figure2_run_dir.resolve()
    output = args.output.resolve()
    generated = output.parent / "generated_input"
    generated.mkdir(parents=True, exist_ok=True)
    archive = theory_dir / "data" / "robust_waveform.npz"
    if not archive.exists():
        raise FileNotFoundError(f"optimized waveform is missing: {archive}")

    progress("Bridge 1/5: compiling the reoptimized waveform into simulator pulses")
    waveform = sampled_gate_waveform(archive)
    progress("Bridge 2/5: calibrating the effective R^-6 blockade anchor")
    blockade_mhz, coherent, calibration_trace = calibrate_blockade(waveform)
    progress(
        f"  B0/(2π)={blockade_mhz:.6g} MHz, "
        f"coherent 1-F={1.0-coherent.average_fidelity:.3e}"
    )
    progress("Bridge 3/5: evaluating the 42-us open-system gate")
    opened = open_system_metrics(waveform, blockade_mhz, coherent.target)
    progress(
        f"  raw 1-F={1.0-opened.raw_average_fidelity:.3e}, "
        f"postselected 1-F={1.0-opened.weighted_conditional_fidelity:.3e}"
    )

    rng = np.random.default_rng(SEED + 10)
    progress("Bridge 4/5: generating finite-shot camera and RB observations")
    imaging = generate_imaging_rows(sim_repo)
    single_rb = rb_rows(
        depths=(1, 2, 4, 8, 16, 32, 64, 96),
        fidelity=0.99935,
        loss_per_gate=1.2e-5,
        shots=SHOTS,
        rng=rng,
        two_qubit=False,
    )
    echoed_rb = rb_rows(
        depths=(1, 2, 4, 8, 16, 24, 32, 48),
        fidelity=opened.weighted_conditional_fidelity,
        loss_per_gate=opened.failure_sink,
        shots=SHOTS,
        rng=rng,
        two_qubit=True,
    )
    sensitivity, decomposition = hessian_panel_rows(theory_dir)
    panel_rows = {
        "fig2a_imaging": imaging,
        "fig2b_single_qubit_rb": single_rb,
        "fig3d_mode_sensitivity": sensitivity,
        "fig3e_channel_decomposition": decomposition,
        "fig4a_waveforms": waveform_rows(theory_dir),
        "fig4b_closed_loop": closed_loop_rows(theory_dir),
        "fig4c_echoed_rb": echoed_rb,
        "fig4d_intensity": intensity_rows(theory_dir),
        "fig4e_stability": stability_rows(
            theory_dir, 1.0 - opened.raw_average_fidelity, rng
        ),
        "fig4f_error_budget": error_budget_rows(
            1.0 - coherent.average_fidelity, opened
        ),
        "pulse_waveform": pulse_waveform_rows(archive),
    }
    panel_paths: dict[str, Path] = {}
    for name, rows in panel_rows.items():
        path = generated / f"{name}.csv"
        write_csv(path, rows)
        panel_paths[name] = path

    progress("Bridge 5/5: writing input.in and simulator comparison metadata")
    write_json(output, manifest(sim_repo, generated, panel_paths))
    summary = {
        "provenance": "simulator synthetic demonstration",
        "shots": SHOTS,
        "seed": SEED,
        "waveform_intervals_in_simulator": waveform.n_samples,
        "effective_blockade_model": "B_eff(R)=B0*(2 um/R)^6",
        "blockade_B0_over_2pi_mhz": blockade_mhz,
        "blockade_calibration_target_raw_infidelity": FINITE_BLOCKADE_ANCHOR,
        "blockade_calibration_trace": calibration_trace,
        "coherent_metrics": {
            "average_fidelity": coherent.average_fidelity,
            "computational_return": coherent.computational_return,
            "local_z_phase_rad": coherent.local_z_phase_rad,
        },
        "open_system_metrics": asdict(opened),
        "paper_comparison_anchors": {
            "figure2_single_qubit_rb_raw_fidelity": 0.99935,
            "figure2_single_qubit_rb_postselected_fidelity": 0.999979,
            "figure4_raw_cz_error": 0.0040,
            "figure4_postselected_cz_error": 0.0010,
            "figure4_erasure_fraction": 0.75,
            "appendix_e_simulated_total_raw": 0.0040,
            "appendix_e_simulated_total_postselected": 0.00066,
        },
        "claim_boundary": [
            "The optimized pulse is an equivalent reoptimization, not the "
            "authors' waveform.",
            "B0 is calibrated to one paper finite-blockade error and is not an "
            "independent MQDT prediction.",
            "The imaging rows are simulator-generated public camera records "
            "using a published fluorescence calibration from a different "
            "neutral-atom experiment.",
            "The Figure-2 RB decay is paper-anchored because the authors' "
            "single-qubit control/noise records are unavailable.",
            "Reported Doppler and laser-noise budget entries remain literal "
            "anchors because the required microscopic samples/PSDs are absent.",
        ],
    }
    write_json(theory_dir / "data" / "simulator_bridge_summary.json", summary)
    figure2_dir.mkdir(parents=True, exist_ok=True)
    write_json(figure2_dir / "data" / "simulator_bridge_summary.json", summary)
    progress(f"Complete: {output}")


if __name__ == "__main__":
    main()
