"""Identity-RG control for the pure multiscale neural VMCRG energy.

For block size one, tau(sigma)=sigma and the exact renormalized Hamiltonian is
H'=H.  This control therefore separates neural representation/optimization
error from the extra operators generated by a genuine b=3 coarse graining.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from scripts.neural_challenge import project, read_json, train, validate, write_json


def run(
    output: Path,
    preset: str,
    fixed_point_map: Path,
    *,
    model_seed: int,
    optimizer_seed: int,
    validation_seed: int,
    projection_seed: int,
) -> dict:
    train(
        output,
        preset,
        fixed_point_map,
        model_seed=model_seed,
        optimizer_seed=optimizer_seed,
        representation="pure",
        block_size=1,
        length_override=15,
    )
    validation = validate(
        output,
        preset,
        seed=validation_seed,
        enforce_formal_gate=False,
    )
    projection = project(
        output,
        preset,
        seed=projection_seed,
        enforce_formal_gate=False,
    )
    config = read_json(output / "config.json")
    passed = validation["status"] == "PASS" and projection["status"] == "PASS"
    result = {
        "status": "PASS" if passed else "FAIL",
        "experiment": "pure_multiscale_neural_identity_rg_control",
        "exact_relation": "block_size=1_implies_H_prime_equals_H",
        "length": config["length"],
        "block_size": config["block_size"],
        "training_steps": config["steps"],
        "fixed_linear_bias_linf": max(abs(x) for x in config["fixed_linear_bias"]),
        "validation": validation["status"],
        "projection": projection["status"],
        "projection_linf_residual": projection["fixed_point_linf_residual"],
        "projection_relative_l2_residual": projection[
            "fixed_point_relative_l2_residual"
        ],
        "model_seed": model_seed,
        "optimizer_seed": optimizer_seed,
        "validation_seed": validation_seed,
        "projection_seed": projection_seed,
    }
    write_json(output / "identity_control_report.json", result)
    print(result, flush=True)
    if preset == "formal" and not passed:
        raise RuntimeError("formal identity-RG control failed")
    return result


def main() -> None:
    parser = argparse.ArgumentParser(description="Pure-neural identity-RG control")
    parser.add_argument("--preset", choices=("smoke", "pilot", "formal"), required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument(
        "--fixed-point-map",
        type=Path,
        default=ROOT
        / "output/reproduction/fixed_point_newton_v2/corrected_rg_v3/summary.json",
    )
    parser.add_argument("--model-seed", type=int, default=202607251)
    parser.add_argument("--optimizer-seed", type=int, default=202607252)
    parser.add_argument("--validation-seed", type=int, default=202607253)
    parser.add_argument("--projection-seed", type=int, default=202607254)
    args = parser.parse_args()
    run(
        args.output.resolve(),
        args.preset,
        args.fixed_point_map.resolve(),
        model_seed=args.model_seed,
        optimizer_seed=args.optimizer_seed,
        validation_seed=args.validation_seed,
        projection_seed=args.projection_seed,
    )


if __name__ == "__main__":
    main()
