use crate::{
    DEFAULT_LIMITS, OccamError, ResourceLimits,
    limits::{checked_add, checked_mul},
};

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ArithmeticOperation {
    Add,
    Multiply,
}

pub fn generate_dataset(
    operation: ArithmeticOperation,
    bits: usize,
    samples: usize,
    seed: u64,
) -> Result<String, OccamError> {
    generate_dataset_with_limits(operation, bits, samples, seed, &DEFAULT_LIMITS)
}

pub fn generate_dataset_with_limits(
    operation: ArithmeticOperation,
    bits: usize,
    samples: usize,
    seed: u64,
    limits: &ResourceLimits,
) -> Result<String, OccamError> {
    if !(1..=32).contains(&bits) {
        return Err(OccamError::Validation(
            "dataset bit width must be in 1..=32".into(),
        ));
    }
    if samples == 0 {
        return Err(OccamError::Validation(
            "sample count must be positive".into(),
        ));
    }
    let input_width = checked_mul(bits, 2, "generated dataset input width")?;
    let mut rng = SplitMix64(seed);
    let operand_mask = (1u64 << bits) - 1;
    let output_width = match operation {
        ArithmeticOperation::Add => checked_add(bits, 1, "addition output width")?,
        ArithmeticOperation::Multiply => checked_mul(bits, 2, "multiplication output width")?,
    };
    limits.require("dataset input width", input_width, limits.max_input_width)?;
    limits.require(
        "dataset output width",
        output_width,
        limits.max_output_width,
    )?;
    limits.require("dataset samples", samples, limits.max_samples)?;
    let row_bits = checked_add(input_width, output_width, "generated dataset row bits")?;
    let dataset_bits = checked_mul(row_bits, samples, "generated dataset bits")?;
    limits.require("dataset bits", dataset_bits, limits.max_dataset_bits)?;
    let row_bytes = checked_add(row_bits, 2, "generated dataset row bytes")?;
    let rows_bytes = checked_mul(row_bytes, samples, "generated dataset rows bytes")?;
    let total_bytes = checked_add(
        "input,output\n".len(),
        rows_bytes,
        "generated dataset bytes",
    )?;
    limits.require("generated bytes", total_bytes, limits.max_generated_bytes)?;
    limits.require("dataset source bytes", total_bytes, limits.max_source_bytes)?;

    let mut output = String::new();
    output.try_reserve_exact(total_bytes).map_err(|error| {
        OccamError::Validation(format!(
            "cannot allocate generated dataset ({total_bytes} bytes): {error}"
        ))
    })?;
    output.push_str("input,output\n");
    for _ in 0..samples {
        let lhs = rng.next() & operand_mask;
        let rhs = rng.next() & operand_mask;
        let result = match operation {
            ArithmeticOperation::Add => lhs + rhs,
            ArithmeticOperation::Multiply => lhs * rhs,
        };
        push_lsb_bits(&mut output, lhs, bits);
        push_lsb_bits(&mut output, rhs, bits);
        output.push(',');
        push_lsb_bits(&mut output, result, output_width);
        output.push('\n');
    }
    Ok(output)
}

fn push_lsb_bits(output: &mut String, value: u64, width: usize) {
    for bit in 0..width {
        output.push(if value & (1u64 << bit) == 0 { '0' } else { '1' });
    }
}

struct SplitMix64(u64);

impl SplitMix64 {
    fn next(&mut self) -> u64 {
        self.0 = self.0.wrapping_add(0x9e3779b97f4a7c15);
        let mut value = self.0;
        value = (value ^ (value >> 30)).wrapping_mul(0xbf58476d1ce4e5b9);
        value = (value ^ (value >> 27)).wrapping_mul(0x94d049bb133111eb);
        value ^ (value >> 31)
    }
}

#[cfg(test)]
mod tests {
    use crate::parse_dataset;

    use super::*;

    fn decode(bits: &[bool]) -> u64 {
        bits.iter().enumerate().fold(
            0,
            |value, (bit, enabled)| {
                if *enabled { value | (1 << bit) } else { value }
            },
        )
    }

    #[test]
    fn generation_is_deterministic_and_seeded() {
        let first = generate_dataset(ArithmeticOperation::Add, 8, 10, 115).unwrap();
        assert_eq!(
            first,
            generate_dataset(ArithmeticOperation::Add, 8, 10, 115).unwrap()
        );
        assert_ne!(
            first,
            generate_dataset(ArithmeticOperation::Add, 8, 10, 116).unwrap()
        );
    }

    #[test]
    fn generated_addition_rows_are_correct() {
        let generated = generate_dataset(ArithmeticOperation::Add, 8, 100, 71).unwrap();
        let dataset = parse_dataset(&generated).unwrap();
        assert_eq!(dataset.input_width, 16);
        assert_eq!(dataset.output_width, 9);
        for sample in dataset.samples {
            assert_eq!(
                decode(&sample.expected),
                decode(&sample.input[..8]) + decode(&sample.input[8..])
            );
        }
    }

    #[test]
    fn generated_multiplication_rows_are_correct() {
        let generated = generate_dataset(ArithmeticOperation::Multiply, 4, 100, 71).unwrap();
        let dataset = parse_dataset(&generated).unwrap();
        assert_eq!(dataset.input_width, 8);
        assert_eq!(dataset.output_width, 8);
        for sample in dataset.samples {
            assert_eq!(
                decode(&sample.expected),
                decode(&sample.input[..4]) * decode(&sample.input[4..])
            );
        }
    }

    #[test]
    fn generation_enforces_limits_before_allocation() {
        let mut limits = DEFAULT_LIMITS;
        limits.max_samples = 1;
        assert!(matches!(
            generate_dataset_with_limits(ArithmeticOperation::Add, 4, 2, 71, &limits),
            Err(OccamError::ResourceLimit {
                resource: "dataset samples",
                ..
            })
        ));

        let mut limits = DEFAULT_LIMITS;
        limits.max_generated_bytes = 1;
        assert!(matches!(
            generate_dataset_with_limits(ArithmeticOperation::Add, 4, 1, 71, &limits),
            Err(OccamError::ResourceLimit {
                resource: "generated bytes",
                ..
            })
        ));
    }
}
